wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/wallpaper1.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/.config/assets/wallpaper1.png
    fit_mode = cover
}

splash = false
